### ISSUE TITLE
failed to run `mvn install`

### ISSUE THREAD

**Issue by michielbdejong** [everis-innolab/ilp-everconnector#1]
I'm new to Maven, but I just tried out `mvn install` in the repo root and it seemed to do something useful, but then it ran into this error:

[ERROR] Failed to execute goal on project plugins: Could not resolve dependencies for project org.everis.interledger:plugins:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.interledger:ilp-core:jar:0.9.2-SNAPSHOT, org.interledger:crypto-conditions:jar:0.4.0-SNAPSHOT: Could not find artifact org.interledger:ilp-core:jar:0.9.2-SNAPSHOT -> [Help 1]

**Comment by earizon** [comment]
@michielbdejong The quilt dependencies must be installed manually at this moment. I updated the README.md file (Installing section) to explain this previous step.

**Comment by michielbdejong** [comment]
Cool, that helped, I now get 'Build Success'! \o/
