### ISSUE TITLE
warning about duplicate declaration

### ISSUE THREAD

**Issue by michielbdejong** [everis-innolab/ilp-everconnector#2]
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.everis.interledger:plugins:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.junit.jupiter:junit-jupiter-api:jar -> duplicate declaration of version 5.1.0-M1 @ line 94, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.vertx:vertx-web-client:jar -> duplicate declaration of version 3.5.0 @ line 116, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 20, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by earizon** [comment]
FIXED
